services:
  - type: web
    name: chatgroove
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: chatgroove
          property: port
    # Add your environment variables here:
    # - key: MONGODB_URI
    #   value: your_mongodb_connection_string
    # - key: JWT_SECRET
    #   generateValue: true
    # - key: GOOGLE_CLIENT_ID
    #   value: your_google_client_id
    # - key: GOOGLE_CLIENT_SECRET
    #   value: your_google_client_secret